### ISSUE TITLE
is this project still maintained?

### ISSUE THREAD

**Issue by nikkicoon** [go-ldap/ldif#22]
It would be good to see potential performance improvements merged, like #18

**Comment by tacerus** [comment]
Wondering the same, it is a useful project but it would be nice not having to maintain a custom fork.

**Comment by cpuschma** [comment]
@tacerus Unfortunately, the project is not currently receiving the attention it requires. However, if you have any commits you would like to share with us, we would be happy to merge them at any time.

Every bit of support counts and is greatly appreciated! ❤️

**Comment by tacerus** [comment]
Thank you for the feedback and for merging the improvements, much appreciated. :)
